### ISSUE TITLE
Insufficient documentation for path: an example is needed

### ISSUE THREAD

**Issue by axelpale** [nylen/easy-tree#1]
Hello and thanks for the lib! I'm currently searching for a good tree lib and `easy-tree` caught my eye. The API seems ok but the docs lack a good example how to use the `path` variable. I think an example is required because the path seems to be an essential parameter in the API.

**Comment by nylen** [comment]
> Most methods take a `path` argument which is an array of 0-based indices that point to a tree node.

For example, `tree.get([0, 3, 1])`.  PR welcome for a good clean way to add example(s) of this.
